### PR TITLE
macOS Big Sur support and buildscripts

### PR DESCRIPTION
**Pull request by threos**
- Added a custom OpenGL package (Official release can't find dynamic libraries on macOS Big Sur)
- Changed sys.path for macOS due to bundle structure
- Added setup.py for macOS that builds an app bundle with necessary packages

### CODE REVIEW

**Comment by joepal1976** [comment]
While I appreciate the effort, this PR seems kind of disproportionate. It adds 132k lines of code, while makehuman itself is only some 46k lines of code. For example, it adds opengl wrappers for opengl on android, which I must assume is redundant for running on macos. 

Is it possible to break out the opengl wrappers to a separate zip file somewhere in order to keep them outside the source code repo? And include/unpack that zip as a part of the build process? We can host that zip file on tuxfamily for example, if it is not already available from somewhere else.

**Review by joepal1976 — CHANGES_REQUESTED** [review]
As per comments above: We should not put the entire opengl wrapper hierarchy under revision control as part of the makehuman source code.

**Comment by threos** [comment]
> As per comments above: We should not put the entire opengl wrapper hierarchy under revision control as part of the makehuman source code.

If we can host the following OpenGL zip, I can make changes in my PR to make setup.py download OpenGL before building instead of having whole OpenGL wrapper in repository :)

[OpenGL.zip](https://github.com/makehumancommunity/makehuman/files/5742111/OpenGL.zip)

**Comment by joepal1976** [comment]
Chrome didn't like that zip, most likely because it contained .pyc files. Since I didn't see any pyc files in the PR, I made a tidied up version where I excluded these, and have made it available at http://download.tuxfamily.org/makehuman/build/macos-opengl-wrapper.zip

Can you check if that file is ok for the build process? If so, then that is the link that can be used.

**Comment by threos** [comment]
I reverted OpenGL commit and updated build script to download and unpack OpenGL at build time.

**Comment by joepal1976** [comment]
Looking good. Going to merge this now. 

Is the drive link on the forum still the build that is relevant to share? In that case, I'll upload it to tuxfamily and make an announcement on facebook that it is available for testing. 

If you have the time and interest in extending the build, my next suggestions would be having the build script download the following links and unzipping them into the plugins directory before building:

- http://download.tuxfamily.org/makehuman/plugins/mhapi-latest.zip
- http://download.tuxfamily.org/makehuman/plugins/assetdownloader-latest.zip
- http://download.tuxfamily.org/makehuman/plugins/socket-latest.zip

I have no idea if these behave as expected on mac though.

**Comment by threos** [comment]
> Looking good. Going to merge this now.
> 
> Is the drive link on the forum still the build that is relevant to share? In that case, I'll upload it to tuxfamily and make an announcement on facebook that it is available for testing.
> 
> If you have the time and interest in extending the build, my next suggestions would be having the build script download the following links and unzipping them into the plugins directory before building:
> 
> * http://download.tuxfamily.org/makehuman/plugins/mhapi-latest.zip
> * http://download.tuxfamily.org/makehuman/plugins/assetdownloader-latest.zip
> * http://download.tuxfamily.org/makehuman/plugins/socket-latest.zip
> 
> I have no idea if these behave as expected on mac though.

I updated buildscript to copy those plugins to /makehuman/plugins before building. I'm creating a new pull request now.

I uploaded latest build to Drive which has community and socket plugins, macOS may give a "macOS cannot verify that this app is free from malware." warning as I can't request a certificate from CA (I don't have an Apple developer account). 
[https://thewiredshopper.com/apple-cannot-check-for-malicious-software-error/](How To Fix Can’t Be Opened Because Apple Cannot Check For Malicious Software)

**Pull request merged**
