### PR TITLE
Removing extra Ms in "Symmmetry"

### PR DESCRIPTION
**Pull request by SerMesh**
Maybe the "Symmmetry" thing should be fixed in 1.2.0? I modified mhmain.py and all language files except Dutch and Portuguese (which don't include the three misspelled strings). A lighter fix could be to leave mhmain.py unmodified, as well as most language files, and to change only the language files where the actually displayed strings are misspelled, namely: master.json, arabic_generic.json, japanese_generic.json, polish_generic.json and romanian_romania.json 

I found no way to modify several files in one commit through GitHub's online interface. Hope that's OK.

### CODE REVIEW

**Comment by joepal1976** [comment]
Thank you. I'll take a look at it. As alpha 2 has already been uploaded, it won't make it into builds until alpha 3 though.

**Comment by SerMesh** [comment]
OK. I would like to contribute corrections to default weights and targets, too. Let me know if that's welcome.

**Comment by joepal1976** [comment]
Updated weight painting is something we need, and I'll welcome pull requests.

Targets are a bit more fragile, as changes in them might cascade (in the case they're macro target) and affect clothing. Which targets specifically do you want to work with?

**Comment by SerMesh** [comment]
The proposed corrections will be nothing radical. I merely mean to enforce the symmetry of the weight groups and targets (and to fix some obvious bugs in the weight maps while I'm at it).
Currently there are many left-right target pairs (or supposedly symmetric single targets) which deform the mesh in non-symmetric ways. I ran into this while making a game character and have been meaning to systematically validate/consolidate MH's data ever since.
Attached is a demonstration of the current symmetry flaws in the targets. I just clicked "Randomize" with the "Symmetry" slider all the way up to 1, which ensures equal contributions on the left and right side of the model. The .mhm file shows that the morph amounts are indeed symmetric, but the actual model is clearly not. That's what I am fixing, and the effect on existing clothes and proxies can only be beneficial.
symmetry

**Comment by joepal1976** [comment]
Sounds fine to me. Ensuring symmetrical targets have been a long standing todo that no-one got around to. 

And the weight painting could really use some love.

**Comment by SerMesh** [comment]
Hi! I already have my own tools and a list of problematic targets/weights, as well as a programmatic auto-fixer. Inspecting/comparing the problematic targets is indeed feasible (by "targets utility" do you mean the custom targets, or some other thing?), and they are also easy to resolve automatically (a simple average between left and right typically does the trick). Inspecting and fixing the weights is much less intuitive, and that's what I'm focused on right now.

**Comment by Aranuvir** [comment]
Inside MakeHuman go to Utilities tab and then Targets. There you can graphically inspect the targets. I'm not sure if averaging the targets is always the best solution. Here is a list of targets with missing or asymmetrical vertices, I have identified:

> Asym:  hip-trans-in.target
> Asym:  hip-trans-out.target
> Asym:  head-trans-in.target
> Asym:  head-trans-out.target
> Asym:  nose-trans-forward.target
> Asym:  nose-curve-concave.target
> Asym:  nose-point-up.target
> Asym:  nose-trans-up.target
> Asym:  nose-trans-in.target
> Asym:  nose-curve-convex.target
> Asym:  nose-greek-decr.target
> Asym:  nose-volume-decr.target
> Asym:  nose-point-down.target
> Asym:  nose-trans-out.target
> Asym:  nose-septumangle-incr.target
> Asym:  female-child-averagemuscle-maxweight-mincup-averagefirmness.target
> Asym:  female-child-averagemuscle-maxweight-mincup-maxfirmness.target
> Asym:  female-child-minmuscle-minweight-mincup-minfirmness.target
> Asym:  female-child-maxmuscle-averageweight-mincup-minfirmness.target
> Asym:  female-old-averagemuscle-maxweight-mincup-maxfirmness.target
> Asym:  female-child-averagemuscle-maxweight-maxcup-minfirmness.target
> Asym:  female-child-minmuscle-maxweight-mincup-averagefirmness.target
> Asym:  female-child-minmuscle-minweight-maxcup-averagefirmness.target
> Asym:  female-old-maxmuscle-averageweight-mincup-maxfirmness.target
> Asym:  female-child-averagemuscle-minweight-maxcup-minfirmness.target
> Asym:  female-old-maxmuscle-averageweight-mincup-minfirmness.target
> Asym:  female-child-maxmuscle-minweight-mincup-averagefirmness.target
> Asym:  female-young-maxmuscle-averageweight-mincup-minfirmness.target
> Asym:  female-child-minmuscle-maxweight-mincup-minfirmness.target
> Asym:  female-child-minmuscle-maxweight-mincup-maxfirmness.target
> Asym:  female-child-minmuscle-averageweight-mincup-maxfirmness.target
> Asym:  female-child-maxmuscle-averageweight-mincup-averagefirmness.target
> Asym:  female-child-averagemuscle-maxweight-mincup-minfirmness.target
> Asym:  female-child-maxmuscle-averageweight-mincup-maxfirmness.target
> Asym:  female-young-minmuscle-minweight-maxcup-minfirmness.target
> Asym:  female-child-minmuscle-averageweight-mincup-minfirmness.target
> Asym:  female-young-maxmuscle-maxweight-mincup-maxfirmness.target
> Asym:  female-child-maxmuscle-minweight-mincup-maxfirmness.target
> Asym:  female-child-minmuscle-minweight-mincup-averagefirmness.target
> Asym:  female-child-averagemuscle-averageweight-mincup-maxfirmness.target
> Asym:  female-old-maxmuscle-averageweight-mincup-averagefirmness.target
> Asym:  female-child-maxmuscle-minweight-mincup-minfirmness.target
> Asym:  female-old-averagemuscle-maxweight-mincup-averagefirmness.target
> Asym:  female-child-averagemuscle-averageweight-maxcup-minfirmness.target
> Asym:  female-child-minmuscle-averageweight-mincup-averagefirmness.target
> Asym:  female-old-maxmuscle-maxweight-maxcup-minfirmness.target
> Asym:  female-young-averagemuscle-minweight-mincup-maxfirmness.target
> Asym:  female-old-minmuscle-minweight-maxcup-averagefirmness.target
> Asym:  female-child-averagemuscle-averageweight-mincup-averagefirmness.target
> Asym:  female-old-averagemuscle-maxweight-mincup-minfirmness.target
> Asym:  female-old-averagemuscle-minweight-maxcup-minfirmness.target
> Asym:  female-old-maxmuscle-averageweight-averagecup-maxfirmness.target
> Asym:  female-child-minmuscle-minweight-mincup-maxfirmness.target
> Asym:  female-child-averagemuscle-averageweight-mincup-minfirmness.target
> Asym:  universal-male-old-maxmuscle-maxweight.target
> Asym:  universal-male-child-minmuscle-averageweight.target
> Asym:  universal-male-young-maxmuscle-averageweight.target
> Asym:  universal-female-young-minmuscle-minweight.target
> Asym:  asian-female-young.target
> Asym:  universal-female-child-maxmuscle-averageweight.target
> Asym:  universal-male-young-maxmuscle-maxweight.target
> Asym:  caucasian-female-young.target
> Asym:  universal-female-child-maxmuscle-maxweight.target
> Asym:  asian-male-child.target
> Asym:  universal-female-child-maxmuscle-minweight.target
> Asym:  caucasian-female-child.target
> Asym:  african-female-old.target
> Asym:  asian-male-old.target
> Asym:  chin-prognathism-decr.target
> Asym:  mouth-lowerlip-width-incr.target
> Asym:  mouth-lowerlip-height-decr.target
> Asym:  mouth-trans-out.target
> Asym:  mouth-scale-vert-incr.target
> Asym:  mouth-lowerlip-middle-down.target
> Asym:  mouth-trans-forward.target
> Asym:  mouth-scale-horiz-decr.target
> Asym:  mouth-lowerlip-width-decr.target
> Asym:  mouth-trans-in.target
> Asym:  mouth-trans-backward.target
> Asym:  mouth-laugh-lines-in.target
> Asym:  mouth-upperlip-width-decr.target
> Asym:  mouth-upperlip-ext-up.target
> Asym:  mouth-lowerlip-middle-up.target
> Asym:  torso-scale-depth-incr.target
> Asym:  torso-scale-depth-decr.target
> Asym:  torso-trans-out.target
> Asym:  torso-scale-vert-incr.target
> Asym:  torso-trans-in.target
> Asym:  measure-waisttohip-dist-decr.target
> Asym:  measure-bust-circ-decr.target
> Asym:  measure-hips-circ-incr.target
> Asym:  measure-hips-circ-decr.target
> Asym:  stomach-tone-decr.target
> Asym:  neck-scale-horiz-decr.target
> Asym:  neck-trans-down.target
> Asym:  neck-scale-depth-decr.target
> Asym:  neck-double-decr.target
> Asym:  neck-trans-forward.target
> Asym:  neck-trans-in.target
> Asym:  neck-scale-depth-incr.target
> Asym:  neck-trans-out.target
> Asym:  l/r-cheek-inner-decr.target
> Asym:  l/r-cheek-inner-incr.target
> Asym:  l/r-lowerleg-scale-horiz-incr.target
> Asym:  l/r-lowerarm-scale-horiz-incr.target
> Asym:  l/r-hand-fingers-distance-decr.target
> Asym:  l/r-leg-valgus-incr.target
> Asym:  l/r-lowerleg-scale-depth-decr.target
> Asym:  l/r-lowerarm-scale-vert-incr.target
> Asym:  l/r-lowerleg-scale-vert-decr.target
> Asym:  l/r-upperarm-muscle-decr.target
> Asym:  l/r-foot-scale-depth-incr.target
> Asym:  l/r-upperarm-scale-vert-incr.target
> Asym:  l/r-lowerarm-scale-vert-decr.target
> Asym:  l/r-lowerleg-scale-horiz-decr.target
> Asym:  l/r-upperarm-scale-horiz-incr.target
> Asym:  l/r-lowerarm-fat-incr.target
> Asym:  l/r-upperarm-fat-decr.target
> Asym:  l/r-foot-trans-forward.target
> Asym:  l/r-foot-scale-horiz-incr.target
> Asym:  l/r-upperarm-scale-horiz-decr.target
> Asym:  l/r-foot-scale-horiz-decr.target
> Asym:  l/r-foot-trans-backward.target
> Asym:  l/r-lowerleg-scale-depth-incr.target
> Asym:  l/r-upperleg-muscle-incr.target
> Asym:  l/r-foot-trans-out.target
> Asym:  l/r-upperleg-fat-incr.target
> Asym:  l/r-hand-fingers-diameter-decr.target
> Asym:  l/r-lowerarm-scale-horiz-decr.target
> Asym:  l/r-upperleg-scale-depth-decr.target
> Asym:  l/r-upperarm-scale-vert-decr.target
> Asym:  l/r-foot-scale-vert-incr.target
> Asym:  l/r-foot-trans-up.target
> Asym:  l/r-upperleg-scale-horiz-incr.target
> Asym:  l/r-lowerarm-scale-depth-decr.target
> Asym:  l/r-upperarm-scale-depth-decr.target
> Asym:  l/r-upperarm-fat-incr.target
> Asym:  l/r-foot-scale-depth-decr.target
> Asym:  l/r-lowerleg-muscle-incr.target
> Asym:  l/r-lowerarm-scale-depth-incr.target
> Asym:  l/r-upperleg-scale-depth-incr.target
> Asym:  l/r-lowerleg-scale-vert-incr.target
> Asym:  l/r-upperarm-shoulder-muscle-decr.target
> Asym:  l/r-leg-valgus-decr.target
> Asym:  l/r-foot-trans-down.target
> Asym:  l/r-upperarm-scale-depth-incr.target
> Asym:  l/r-upperleg-scale-horiz-decr.target
> Asym:  l/r-ear-shape-triangle.target
> Asym:  l/r-ear-shape-square.target
> Asym:  l/r-ear-scale-depth-decr.target
> Asym:  l/r-ear-shape-pointed.target
> Asym:  l/r-ear-flap-decr.target
> Asym:  l/r-ear-trans-down.target
> Asym:  l/r-ear-trans-forward.target
> Asym:  l/r-ear-shape-round.target
> Asym:  l/r-ear-lobe-decr.target
> Asym:  l/r-ear-scale-depth-incr.target
> Asym:  l/r-ear-trans-backward.target
> Asym:  l/r-ear-trans-up.target
> Asym:  l/r-ear-lobe-incr.target
> Asym:  l/r-ear-scale-decr.target
> Asym:  l/r-ear-scale-vert-decr.target
> Asym:  l/r-ear-flap-incr.target
> Asym:  l/r-ear-rot-forward.target
> Asym:  l/r-ear-rot-backward.target
> Asym:  l/r-eye-height1-decr.target
> Asym:  l/r-eye-height2-incr.target
> Asym:  l/r-eye-eyefold-concave.target
> Asym:  l/r-eye-corner1-down.target
> Asym:  l/r-eye-push1-in.target
> Asym:  l/r-eye-push1-out.target
> Asym:  l/r-eye-trans-in.target
> Asym:  l/r-eye-corner1-up.target
> Asym:  l/r-eye-height1-incr.target
> Asym:  l/r-eye-corner2-down.target
> Asym:  l/r-eye-bag-height-incr.target
> Asym:  l/r-eye-height3-decr.target
> Asym:  l/r-eye-trans-out.target
> Asym:  l/r-eye-trans-down.target
> Asym:  l/r-eye-corner2-up.target
> Asym:  l/r-eye-bag-incr.target
> Asym:  l/r-eye-scale-incr.target
> Asym:  l/r-eye-push2-in.target
> Asym:  l/r-eye-push2-out.target
> Asym:  l/r-eye-epicanthus-out.target
> Asym:  l/r-eye-trans-up.target
> Missing:  nose-curve-concave.target
> Missing:  nose-point-up.target
> Missing:  nose-trans-in.target
> Missing:  nose-curve-convex.target
> Missing:  nose-volume-decr.target
> Missing:  nose-point-down.target
> Missing:  nose-trans-out.target
> Missing:  nose-septumangle-incr.target
> Missing:  female-old-averagemuscle-maxweight-mincup-maxfirmness.target
> Missing:  female-young-averagemuscle-maxweight-mincup-averagefirmness.target
> Missing:  female-old-maxmuscle-averageweight-mincup-maxfirmness.target
> Missing:  female-child-averagemuscle-minweight-maxcup-minfirmness.target
> Missing:  female-old-maxmuscle-averageweight-mincup-minfirmness.target
> Missing:  female-young-averagemuscle-maxweight-mincup-minfirmness.target
> Missing:  female-old-maxmuscle-averageweight-mincup-averagefirmness.target
> Missing:  female-young-averagemuscle-maxweight-mincup-maxfirmness.target
> Missing:  female-old-averagemuscle-maxweight-mincup-averagefirmness.target
> Missing:  female-old-maxmuscle-maxweight-maxcup-minfirmness.target
> Missing:  female-old-averagemuscle-maxweight-mincup-minfirmness.target
> Missing:  female-old-averagemuscle-minweight-maxcup-minfirmness.target
> Missing:  universal-female-child-maxmuscle-maxweight.target
> Missing:  chin-width-decr.target
> Missing:  upperlegs-height-decr.target
> Missing:  mouth-lowerlip-width-incr.target
> Missing:  mouth-upperlip-middle-down.target
> Missing:  mouth-cupidsbow-decr.target
> Missing:  mouth-lowerlip-height-decr.target
> Missing:  mouth-trans-out.target
> Missing:  mouth-scale-vert-incr.target
> Missing:  mouth-upperlip-middle-up.target
> Missing:  mouth-lowerlip-middle-down.target
> Missing:  mouth-trans-forward.target
> Missing:  mouth-scale-horiz-decr.target
> Missing:  mouth-lowerlip-width-decr.target
> Missing:  mouth-trans-in.target
> Missing:  mouth-trans-backward.target
> Missing:  mouth-laugh-lines-in.target
> Missing:  mouth-upperlip-width-decr.target
> Missing:  mouth-upperlip-ext-up.target
> Missing:  torso-scale-depth-incr.target
> Missing:  torso-scale-depth-decr.target
> Missing:  torso-scale-vert-incr.target
> Missing:  measure-bust-circ-decr.target
> Missing:  measure-upperleg-height-decr.target
> Missing:  measure-hips-circ-incr.target
> Missing:  measure-hips-circ-decr.target
> Missing:  l/r-cheek-inner-decr.target
> Missing:  l/r-cheek-inner-incr.target
> Missing:  l/r-lowerleg-scale-horiz-incr.target
> Missing:  l/r-lowerarm-scale-horiz-incr.target
> Missing:  l/r-hand-fingers-distance-decr.target
> Missing:  l/r-lowerleg-scale-depth-decr.target
> Missing:  l/r-lowerarm-scale-vert-incr.target
> Missing:  l/r-lowerleg-scale-vert-decr.target
> Missing:  l/r-upperarm-muscle-decr.target
> Missing:  l/r-foot-scale-depth-incr.target
> Missing:  l/r-upperarm-scale-vert-incr.target
> Missing:  l/r-lowerarm-scale-vert-decr.target
> Missing:  l/r-lowerleg-scale-horiz-decr.target
> Missing:  l/r-foot-scale-vert-decr.target
> Missing:  l/r-upperarm-scale-horiz-incr.target
> Missing:  l/r-lowerarm-fat-incr.target
> Missing:  l/r-upperarm-fat-decr.target
> Missing:  l/r-foot-trans-forward.target
> Missing:  l/r-foot-scale-horiz-incr.target
> Missing:  l/r-upperarm-scale-horiz-decr.target
> Missing:  l/r-foot-scale-horiz-decr.target
> Missing:  l/r-foot-trans-backward.target
> Missing:  l/r-lowerleg-scale-depth-incr.target
> Missing:  l/r-upperleg-muscle-incr.target
> Missing:  l/r-foot-trans-out.target
> Missing:  l/r-upperleg-fat-incr.target
> Missing:  l/r-lowerarm-scale-horiz-decr.target
> Missing:  l/r-upperleg-scale-depth-decr.target
> Missing:  l/r-upperarm-scale-vert-decr.target
> Missing:  l/r-foot-scale-vert-incr.target
> Missing:  l/r-foot-trans-up.target
> Missing:  l/r-upperleg-scale-horiz-incr.target
> Missing:  l/r-lowerarm-scale-depth-decr.target
> Missing:  l/r-upperarm-scale-depth-decr.target
> Missing:  l/r-upperarm-fat-incr.target
> Missing:  l/r-foot-scale-depth-decr.target
> Missing:  l/r-lowerleg-muscle-incr.target
> Missing:  l/r-lowerarm-scale-depth-incr.target
> Missing:  l/r-upperleg-scale-depth-incr.target
> Missing:  l/r-lowerleg-scale-vert-incr.target
> Missing:  l/r-upperarm-shoulder-muscle-decr.target
> Missing:  l/r-foot-trans-down.target
> Missing:  l/r-upperarm-scale-depth-incr.target
> Missing:  l/r-foot-trans-in.target
> Missing:  l/r-upperleg-scale-horiz-decr.target
> Missing:  l/r-ear-shape-triangle.target
> Missing:  l/r-ear-shape-square.target
> Missing:  l/r-ear-scale-depth-decr.target
> Missing:  l/r-ear-shape-pointed.target
> Missing:  l/r-ear-flap-decr.target
> Missing:  l/r-ear-trans-down.target
> Missing:  l/r-ear-trans-forward.target
> Missing:  l/r-ear-shape-round.target
> Missing:  l/r-ear-lobe-decr.target
> Missing:  l/r-ear-scale-vert-incr.target
> Missing:  l/r-ear-scale-depth-incr.target
> Missing:  l/r-ear-scale-incr.target
> Missing:  l/r-ear-trans-backward.target
> Missing:  l/r-ear-trans-up.target
> Missing:  l/r-ear-lobe-incr.target
> Missing:  l/r-ear-scale-decr.target
> Missing:  l/r-ear-scale-vert-decr.target
> Missing:  l/r-ear-rot-forward.target
> Missing:  l/r-ear-rot-backward.target
> Missing:  l/r-eye-height1-decr.target
> Missing:  l/r-eye-height2-incr.target
> Missing:  l/r-eye-eyefold-concave.target
> Missing:  l/r-eye-corner1-down.target
> Missing:  l/r-eye-push1-in.target
> Missing:  l/r-eye-push1-out.target
> Missing:  l/r-eye-trans-in.target
> Missing:  l/r-eye-corner1-up.target
> Missing:  l/r-eye-height1-incr.target
> Missing:  l/r-eye-corner2-down.target
> Missing:  l/r-eye-bag-height-incr.target
> Missing:  l/r-eye-height3-decr.target
> Missing:  l/r-eye-trans-out.target
> Missing:  l/r-eye-trans-down.target
> Missing:  l/r-eye-corner2-up.target
> Missing:  l/r-eye-bag-incr.target
> Missing:  l/r-eye-scale-incr.target
> Missing:  l/r-eye-push2-in.target
> Missing:  l/r-eye-push2-out.target
> Missing:  l/r-eye-epicanthus-out.target
> Missing:  l/r-eye-trans-up.target

**Comment by SerMesh** [comment]
Thanks.
1) The only tabs I see under Utilities, both for 1.1.1 and 1.2.0a1, are "Logs" and "Expression mixer", although I do have a bunch of other 7_*.py files in the "plugins" folder. Am I supposed to activate those plugins somehow?
2) I generated the same lists as you, although I saw no reason to distinguish between "Missing:" and "Asym;" unless/until the morphs are analyzed in more detail. A "missing" vertex can be something as benign as a 0 amount on one side and 0.0001 on the other, so it's just another case of more or less minor asymmetry, and the fix will be exactly the same.
3) Indeed left-right averaging is not always the solution. There are many cases where the modeler messed up the morph or weight map without noticing, and resolving such cases requires some "love" as Joel said.

**Comment by SerMesh** [comment]
P.S. Sorry, the 0 vs 0.0001 example was more relevant to the weights. Targets work with integer increments.

**Comment by Aranuvir** [comment]
@1: Yes, sorry, you need to activate those plugins. I thought in the alpha they where not excluded from activation...

@2: Targets use float values, too. And I must admit, that a tiny difference of some 0.001 probably won't be visible. Therefore I've implemented a threshold in my script, but for the list above it was set to 0.

Maybe we should open a separate topic for this discussion.

**Comment by SerMesh** [comment]
I am not too familiar with gitHub, so we can continue however you wish (email, maybe?)
I am curious about the activation of the "hidden" plugins. Never realized they were there.

**Comment by joepal1976** [comment]
I've opened a new issue for symmetrical targets in #21

**Pull request merged**
